services:
  hi-flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/hi_flask
    volumes:
      - .:/app:ro
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: hi_flask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
